version: '3'

services:
  redis:
    image: redis:alpine
    environment:
      - DOMAIN_NAME=redis.${BASEHOST:-pimcore.docker}

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-toor}
      - DOMAIN_NAME=mysql.${BASEHOST:-pimcore.docker}
    command: --innodb-doublewrite=0 --innodb-large-prefix=1 --innodb-file-format=Barracuda --innodb-page-size=32K

  mailcatcher:
    image: mailhog/mailhog
    environment:
      - DOMAIN_NAME=mailcatcher.${BASEHOST:-pimcore.docker}

  application:
    image: ${DOCKER_ID_USER:-wselcon}/php-pimcore:${PHPVERSION:-7.1}
    environment:
      - C_UID=${C_UID:-1000}
      - C_GID=${G_UID:-1000}
      - DEVELOPMENT=${DEVELOPMENT:-1}
    volumes:
      - ${APPLICATION:-../app}:/phpapp
    links:
      - mysql
      - redis
      - mailcatcher

  nginx:
    image: ${DOCKER_ID_USER:-wselcon}/nginx-pimcore${PIMCOREVERSION:-5}:${NGINXVERSION:-stable}
    environment:
      - VIRTUAL_HOST=${BASEHOST:-pimcore.docker},${EXTRAHOSTS}
    volumes:
      - ${APPLICATION:-../app}:/phpapp
    links:
      - application